### ISSUE TITLE
support cors or jsonp for countries.json?

### ISSUE THREAD

**Issue by gregglind** [mozilla/geodude#10]
(Or don't!)

**Comment by Osmose** [comment]
I'd say adding CORS headers would be the correct move.

**Comment by gregglind** [comment]
All right, who does what there?  Risks of public usage?  Etc.

**Comment by Osmose** [comment]
All we need is a quick patch to add the right headers to this service (and I'm assuming currently that @willkg is going to provide this whenever he gets around to that part of his work on adding geo to heartbeat), then I'll merge and you talk to jakem about when he's available to deploy the update.

There's no increased risk of public usage because the public already can use the JavaScript endpoint, so we already live with that risk.

**Comment by willkg** [comment]
I'm game for doing this. Just waiting on @gregglind to say, "yes--can't do what i want any other way. let's do this cors thing!"

**Comment by gregglind** [comment]
I don't thing CORS will be necessary here.  Will revisit if getting GEO in firefox generally turns into a Thing Worth Doing.  Thanks for looking into it!
